language: php
php:
  - 7.0
  - 7.1
env:
  global:
    - DEFAULT=1
matrix:
  include:
    - php: 5.4
      env: PHPCS=1 DEFAULT=0

  allow_failures:
    - env: PHPCS=1 DEFAULT=0
    - php: 7.0
    - php: 7.1
before_script:
  - composer self-update
  - composer install
notifications:
  email: false
